### ISSUE TITLE
Task: Improve L&I classifications

### ISSUE THREAD

**Issue by nlebovits** [CodeForPhilly/clean-and-green-philly#164]
I'd like to do the following for L&I:

1) Get a list and count of all open L&I violations + complaints at a property
2) Get a list and count of all open L&I blight violations + complaints at a property
3) Get a list and count of all L&I blight violations + complaints at a property in the past year

First, though, I will need to look at all possible L&I violation and complaint codes and figure out what we want to count as blight. I need to do this.

I've gone through the dataset to do some QC based on access process and priority level. Here's what I'm seeing:

**Comment by Moylena** [comment]
License and inspections. TBD what is the best formula - working session needed

**Comment by nlebovits** [comment]
closed by #951
