### ISSUE TITLE
Task: Add "Get Support" resource page

### ISSUE THREAD

**Issue by willonabike** [CodeForPhilly/clean-and-green-philly#258]
Add a resource that includes a deeper guide to resources to help with Transform.
Add into navigation under Take Action
Content will be developed by Lahy.

**Comment by Moylena** [comment]
Still active - grant, legal, etc support

**Comment by Moylena** [comment]
Need to write and design before creating related tickets - 1st iteration for summer workshops

**Comment by nlebovits** [comment]
Punting to UX team for a re-design
