### ISSUE TITLE
Dataset: improve ID of city-owned properties

### ISSUE THREAD

**Issue by nlebovits** [CodeForPhilly/clean-and-green-philly#284]
The PLB dataset is not enough to identify city-owned projects. We'll have to use string-matching like I did in my old script to flag these properties and possibly turn them to "Do Nothing" like the others. 

![image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/111617674/2ee2f913-e499-41a8-957e-a0f973afd3fa)

**Comment by thansidwell** [comment]
@nlebovits I don't quite understand this ticket. Is it still relevant?

**Comment by nlebovits** [comment]
closed by #681
