### ISSUE TITLE
Content: Give Users warning about data accuracy

### ISSUE THREAD

**Issue by willonabike** [CodeForPhilly/clean-and-green-philly#285]
Use case: Give people suitable warning to their due dilligence on properties + that our dataset contains some errors. 
Maybe an info banner on the map view, that "remembers" not to show once has already closed it.

**Comment by Moylena** [comment]
@nlebovits @thansidwell would the existing legal disclaimer cover this or do we think it merits another call out? If not, I can archive.

**Comment by nlebovits** [comment]
Good idea, easy to implement. Need a design, so will punt to UX team.
