### ISSUE TITLE
A11y: Consider renaming " x Properties in view" to make it more accurate

### ISSUE THREAD

**Issue by marvieqa** [CodeForPhilly/clean-and-green-philly#318]
## Description

The label ` X Properties in View` doesn't accurately describe what is shown on the page.  We don't actually show all those properties in the current view as they are spread over different pages.  

Also, the current view only shows 6 properties per page. It will be helpful to communicate that as well.

## Recommendation
- Consider renaming it to `X Total Properties` instead.

  <details>
  <summary> Screenshot </summary>

  <img width="1311" alt="Screenshot 2024-02-07 at 19 04 39" src="https://github.com/CodeForPhilly/vacant-lots-proj/assets/102739972/866a3b02-6eb9-4e1c-94e9-08d5eb2c3283">

  </details>

- Add some sort of a counter at the bottom of the page to say `1-6 of 100` (close to the note that says we only display 100)

  <details>
  <summary> sample </summary>

  <img width="381" alt="Screenshot 2024-02-07 at 19 59 23" src="https://github.com/CodeForPhilly/vacant-lots-proj/assets/102739972/94f24400-64ce-4c85-beb7-d069f2268717">

  </details>

**Comment by bacitracin** [comment]
Also in favor of renaming. "in view" seems like ableist language for blind folks

**Comment by amyyeung17** [comment]
Hi I would like to be assigned this :)

**Comment by bacitracin** [comment]
@amyyeung17 assigned!
