### ISSUE TITLE
A11y: Info Icon is hard to see in WHCM

### ISSUE THREAD

**Issue by bacitracin** [CodeForPhilly/clean-and-green-philly#334]
## Describe the task
1. When in Windows High Contrast Mode / dark the info icon is hard to see.
<img width="256" alt="Screenshot 2024-02-10 at 3 10 13 PM" src="https://github.com/CodeForPhilly/vacant-lots-proj/assets/7329799/e87e7679-cab6-43fa-b340-ee0fb966225c">

Note: the filter buttons & the actual map buttons are also hard to see, but they are separate tickets. 

## Acceptance Criteria

Open the page in WHCM or simulate it using Devtools(see link below)
- [ ] The info icon will be easier to see/ not dark gray in dark mode -  will probably be white
- [ ] Be sure to check light mode as well

## Additional context

* https://www.smashingmagazine.com/2022/06/guide-windows-high-contrast-mode/
* How to simulate WHCM in Chrome Devtools - https://devtoolstips.org/tips/en/emulate-forced-colors/

**Comment by thansidwell** [comment]
How did you determine it's hard to see? I'm guessing it passes AA. Or is the problem that it should turn white like the text does? 

Also, my latest design work illuminates the info icons in favor of description text, so maybe it's not worth it? https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=3696%3A40889&mode=design&t=7DBdjo6bPKuc4PzF-1

**Comment by bacitracin** [comment]
@thansidwell This ticket & any other with "WHCM" refers specifically to using the site in WIndows High Contrast Mode, which you can simulate in Chrome Devtools. https://devtoolstips.org/tips/en/emulate-forced-colors/. 

Ideally the info icon would be white like the text. If we are removing the info icons, then this ticket can be closed.

**Comment by bacitracin** [comment]
Design has changed and there are no info icons in the filter panel, so this ticket no longer applies.
