### ISSUE TITLE
Content: Add date to photo of property on map detail page

### ISSUE THREAD

**Issue by Moylena** [CodeForPhilly/clean-and-green-philly#425]
Pull in [relevant date] and overlay that text over the property image on the bottom right hand side

Pull date from the Google Street View capture images

**Comment by Moylena** [comment]
Need to establish where to pull the date from before moving this to "To Do"

**Comment by nlebovits** [comment]
Closing--not technically feasible. Google allows manual checking of dates with Maps in browser, but not in automated way via API.
