### ISSUE TITLE
Task: Replace Mapbox geocoder with Maptiler

### ISSUE THREAD

**Issue by brandonfcohen1** [CodeForPhilly/clean-and-green-philly#469]
## Describe the task
Replace Mapbox geocoder with Maptiler

## Acceptance Criteria

- [ ] Remove and replace `@mapbox/mapbox-gl-geocoder` with a solution that uses the Maptiler API
- [ ] Update npm packages accordingly
- [ ] Ensure no functionality loss

**Comment by Moylena** [comment]
@brandonfcohen1  hey! Is this required for the competition?

**Comment by brandonfcohen1** [comment]
> @brandonfcohen1 hey! Is this required for the competition?

no
