### ISSUE TITLE
Feature request: changelog for Data Refresh

### ISSUE THREAD

**Issue by brandonfcohen1** [CodeForPhilly/clean-and-green-philly#520]
**Is your feature request related to a problem? Please describe.**
When the data is refreshed, we should track changes and make sure to archive old data.

**Describe the solution you'd like**
Add to the data refresh the following:
- Back up the old dataset locally and on Google Cloud
- Calculate the # of properties added and removed
- Prepare a notification email or slack message with the diff details

**Comment by zigouras** [comment]
@brandonfcohen1 is this a diff of the data in postgres or in the static tile file?  How should I approach this?  Thanks.  You can assign to me.

**Comment by brandonfcohen1** [comment]
Hey @zigouras- would definitely be easier in postgres

**Comment by zigouras** [comment]
I did an audit of the tables in the postgres db to see if I could determine what the primary key columns should be.  I need to enforce primary keys on any tables analyzed in by the data-diff program.  So far I have vacant_properties working, which is the main table from my understanding, but I would like to diff as many tables as possible.

The grid below lists the tables, my best guess at the pk columns, the number of rows with unique values in those columns, the total number of rows if different from the unique rows, and any condition applied to get the row counts.

| Table|pk columns|Unique rows|Total rows|Condition
| -------- | ------- |-------- | ------- |-------- |
|drug_crimes|x, y, dispatch_date|2596 |2691|
|gun_crimes|x, y, dispatch_date|5120|5136|
|imminently_dangerous_buildings|opa_account_num|281|296|
|li_complaints|service_request_id|246309||
|li_violations|violationnumber, opa_account_num|95920|||
|opa_properties|parcel_number|582970|||
|phs_properties|brt_id|9044|9051||
|property_tax_delinquencies|opa_number|54398||opa_number <> 0|
|rcos|OBJECTID|251|||
|spatial_ref_sys|srid|8500|||
|unsafe_buildings|opa_account_num|3684|3791|opa_account_num is not null

Some tables like li_complaints are simple and clean, others need to be cleaned up and still there are some discrepancies.  @brandonfcohen1 can you take a look and comment on this metadata?  Can I apply the cleanup steps, e.g. deleting the rows in property_tax_delinquencies where opa_number <> 0, after the data has been loaded in postgres, or do those rows have to be removed from the Geopandas object first so the map features do not get generated?

**Comment by zigouras** [comment]
pr created, please review:
https://github.com/CodeForPhilly/clean-and-green-philly/pull/632
