### ISSUE TITLE
Simplify & combine "Get Access" filter

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/clean-and-green-philly#581]
The filter has some usability issues.

- These different filters are actually different methods of getting access, but they are grouped in seperated field groups likely to created confusion. 
  - Buy Property, Land Bank, Private Land Use Agreement, Conservatorship Eligible, Side Yard Eligable and Tactical Urbanism
- Most methods like "Land Bank, Private Land Use Agreement, and Conservatorship are likely hard to understand for the lay person. They need more explaination for people to understand if they are good options for them. 
- The logic of how these filters work isn't the same which will likely also confuse people. 
  - Filtering by Buy Property Land Bank, Private Land Use Agreement will show operties where the option is the **_best option_**.
  - Filtering by Conservatorhips, Side Yard, and Tactical Urbanism will show properties where the option is **_avaliable_**. 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/e99e6ed8-1ac1-43dd-9c2f-0cda40dd06cd)

Make these these changes to address those issues

- Create a new selectable panel for each filter 
  - Add an icon for each to help with recognition
  - Add heading and description to bring clarity to what they mean
  - Clicking on it changes it to a selected state with a blue background a check mark
  - Build in the Hovering and Pressing states as well [View prototype](https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=6340%3A41341&mode=design&t=Pbc7oHPHsvr5J4Sr-1)

- Filtering by these options would filter to properties where those options are the either "Avaliable" or the "Best Option." 

- Add a "Find only when it's best option" badge button
  - Clicking this button would filter to properties where those options are the "best option"

- Delete the old sections

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/f2af258f-9112-46d7-b2b7-214d2f62c3ec)

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/13c6c0a3-16d3-4142-8424-95d159feae24)

All these changes harmonizes with the improved "Get Access" section, making is 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/6d4a7353-9047-4900-a5f7-bee58885a41e)

**Comment by jgrimes86** [comment]
@thansidwell I'd like to work on this issue, but I have a question about the 'Find only when its the best option' button.

As said in the issue description, the "Access Process" buttons are filtering for when "Buy Property", "Land Bank", and "Private Land Use Agreement" are considered the best options.  If I understand the "Getting Access" section correctly, it includes a "best option" card simply if the property features one of those access methods.

My understanding of the new panel filter is that the panels are supposed to do the same thing as those current filter buttons, so the user would still already be selecting properties where one of those is the best option.  What filtering is the "Find only when its the best option" supposed to add?

**Comment by thansidwell** [comment]
@jgrimes86 Yes, the current logic was built, so that properties can only have one of "Buy Property", "Land Bank", and "Private Land Use Agreement." According to Nissim, they seem to be practically mutually exclusive. And we do make that one option the "Best Option." I didn't mention that above. 

That does make me wonder if the 'Find only when its the best option' button would actually be useful? 

- For those three main options they are always made the "Best Option." If you toggled on and off the "Find only best" button with these there would be no difference. 
- Also options like Sideyard, Conservatorship, and Tactical Urbanism are never the best option the way the logic works today. If you toggled on and off the "Find only best" button with these, they would just all completely disappear and then reappear. 

So perhaps the 'Find only when its the best option' button isn't actually useful.

**Comment by thansidwell** [comment]
@jgrimes86 
I just realized we could simplify this ticket a lot by taking out all the new UI work, and just moving the options to the new section. All the new UI work could be a separate ticket. Do you have a preference? 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/a851e9a8-86ae-430b-832f-7ebfb7124ce6)

**Comment by jgrimes86** [comment]
@thansidwell  I think I can take care of the styling with this ticket

**Comment by nlebovits** [comment]
closed by #600
