### ISSUE TITLE
Reword Filters

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/clean-and-green-philly#592]
Reword these filters 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/e40271b8-5fd8-4a20-8117-11a62ba5b8e3)

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/5e320ae2-b7e2-41c3-a590-7c31c98f2482)

- Change "Parcel Type" to "Property Type" 
  - We are using the term property throughout the website. 
- Change "LLC Owner" to "Owner" 
    - LLC some people may not know.
- Change "Yes" to "Business"
- Change "No" to "Individual" 
    - This is a more clear explanation of the options.

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/a05cf405-2f8a-44a4-87d8-b4d836d3e677)

**Comment by zheyichn** [comment]
Hi! May I be assigned this issue?

**Comment by zheyichn** [comment]
I have updated the filter option content ([draft PR](https://github.com/CodeForPhilly/clean-and-green-philly/pull/695)), but the filtering is malfunctioning. Any thought @CodeWritingCow? 
- Screen-recording as below:
https://github.com/CodeForPhilly/clean-and-green-philly/assets/88219993/894250b5-15ab-499f-8f1e-b07620a63365

**Comment by CodeWritingCow** [comment]
@zheyichn great catch! It seems if we change the option names (`Yes/No` to `Business/Individual`), then our filtering UI returns zero results. As a comparison, here's a screen recording of our current UI with the `Yes/No` options for "Owner." Note how it returns filtered results as expected:

https://github.com/CodeForPhilly/clean-and-green-philly/assets/7751862/4ee5e0b5-3c84-41f5-9ab9-c8e6803b5520

I see at least two different ways to resolve this:

1. Modify the Python pipeline as your draft PR is doing. However, I'm not sure how this would alter our data. Before continuing with this approach, it's best if you discuss it first with @nlebovits, @brandonfcohen1 or @zigouras. They are more knowledgeable about the data pipeline.
2. Don't modify the Python scripts. Keep the `Yes/No` option values "under the hood" but display their text in the UI as `Business/Individual` "on the surface.

What do you think?

**Comment by zheyichn** [comment]
Hi @CodeWritingCow, thanks for your inputs! I think option2 is easier at this moment and we can always come back to refactor the script later if needed. I have made some changes accordingly to adpat display flexibility [here](https://github.com/CodeForPhilly/clean-and-green-philly/pull/697). 
Can you review it when you get a second? 

If option1 is preferred, I am happy to dig more into the backend.

**Comment by CodeWritingCow** [comment]
Hi @zheyichn, I've reviewed and approved your PR. Your solution allows front-end developers to be flexible with button text, so they don't have to be concerned with the backend. Thanks for looking into this!
