### ISSUE TITLE
Adjust dot to geometry switch on map

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/clean-and-green-philly#593]
When the map loads the properties show up as dots. As you zoom in the dots switch to showing the geometry of the properties.

https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/6094ce20-7924-4ae3-9f11-00771796a7cb

- The switch is jarring, with the properties almost seeming to disappear.
- The dots at that level are quite dense and form a thick strong pattern.
- The geometric properties shapes at that level are very small.

I recommend we change the point at which the switch happens to be at a lower zoom level
- The dots will be more spaced out
- The geometric properties shapes will be larger
- The transition won't be so dramatic

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/09277db3-a561-4fe4-b481-3c946c7fc288)

Perhaps at a level like this. I'd recommend experimenting until it feels right. 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/9e19ebd5-f481-45cb-b50b-4f0f20c316d2)

**Comment by Moylena** [comment]
Hi @brandonfcohen1  is this done? I know you're signing off the project but want to understand where we are
