### ISSUE TITLE
Fix property list controls

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/clean-and-green-philly#594]
Fix the styling of the property list controls

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/8fb5d4a3-ac06-448c-9573-1a642cc8de8f)

To match the prototype

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/5247928e-a228-4e01-a774-557a808617ff)

And match the single property controls

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/941fe1b9-364e-4754-a90e-87e2c09d76e1)

 - Ensure the padding matches the prototype
 - Remove the bottom border line
 - Remove the extra padding around the text

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/7e0f7df6-ab7f-468c-a503-2094887a8792)

**Comment by Moylena** [comment]
Is there an associated PR for this? I don't see anything in this audit trail @AZBL

**Comment by AZBL** [comment]
> Is there an associated PR for this? I don't see anything in this audit trail @AZBL

There should be I though lt it was done but I’ll check later

**Comment by AZBL** [comment]
> Is there an associated PR for this? I don't see anything in this audit trail @AZBL

@Moylena 
#611 
https://github.com/CodeForPhilly/clean-and-green-philly/pull/611

**Comment by Moylena** [comment]
Thanks, please tag the ticket you are closing on each PR so it tracks back!
