### ISSUE TITLE
Accept or Decline Cookies

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/clean-and-green-philly#597]
People need a way to 

- Save properties to a list (in development)
- Preserve the filters (not yet built)
  - So when you click on a Get Access option and go back you don't have to enter your filters manually again. 
- Preserve their location and zoom level on the map
  - So when you go to another page and come back to the map you return to where you were

We decided that the best way to do that is with cookies. However we also need to 

- Let users know we are saving cookies into their browser
- Give them an option to decline
- If they decline, show them they need to accept it to use certain features

Here's the experience broken down. 

### Banner
- When users go to the website a banner appears at the bottom of the viewport fixed to the bottom. 
  - Add a blue background, heading, description, decline button and accept button matching the [prototype](https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=6687%3A49263&mode=design&t=N70QHaaNsyW7ez2E-1).
  - The banner should appear on every page you visit. 
- When you click "Accept"
  - The banner will disappear
  - We can then store cookies to their browser. 
- Clicking "Decline" 
  - The banner will disappear
  - We do not store cookies to their browser. Perhaps we should delete any cookies that we have saved to their browser at that moment. 

### Footer 
- On a footer there's a new "Cookie Settings" link 
- Rework the footer so all the elements are center aligned and seperated by "  —  "
  - When they are spread out they draw more attention to themselves than needed
- Clicking this will make the banner appear again so users can change their choice

### Save Button
- On a property, when a user clicks "Save" 
- If they have **_accepted_** cookies the property is saved as expected
- If they have **_declined_** cookies the banner appears again
- If they decline again the property does not save
- If they accept then the property is saved as expected 

https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/bbb5c7c4-8fd2-48ca-925a-30ae64115a65

[View the Prototype](https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=6687%3A49263&mode=design&t=N70QHaaNsyW7ez2E-1)

**Comment by CodeWritingCow** [comment]
@thansidwell can you assign this ticket to me? Thanks!

By the way, the video shows the "Decline" button preceding the "Accept" button. In general, I think it's more common for "Accept" to precede "Decline" in website UIs. Also, would it be better if "Accept" appears first, so users might be more encouraged to click "Accept"?

**Comment by thansidwell** [comment]
@CodeWritingCow, Done!

I hear you on the order. It's actually debatable topic in UX. For instance Windows puts the primary action first while Apple puts it last. Here's [an article](https://www.nngroup.com/articles/ok-cancel-or-cancel-ok/) about it. I'm persuaded that the primary action last is the better approach. 

<img width="1016" alt="CleanShot 2024-04-29 at 23 46 23@2x" src="https://github.com/CodeForPhilly/clean-and-green-philly/assets/1965986/de83f4f5-8314-4ce8-a500-046b6fdbf21c">

**Comment by CodeWritingCow** [comment]
> @CodeWritingCow, Done!
> 
> I hear you on the order. It's actually a debatable topic in UX. For instance, Windows puts the primary action first while Apple puts it last. Here's [an article](https://www.nngroup.com/articles/ok-cancel-or-cancel-ok/) about it. I'm persuaded that the primary action last is the better approach.
> 
@thansidwell Thanks for sharing the article. It was a great read. On this UX topic, I'll defer to you and follow your design!

**Comment by Moylena** [comment]
Pending final review and approval
