### ISSUE TITLE
Map height too tall on mobile

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/clean-and-green-philly#598]
When people view the "Find Properties" page on mobile the page is too tall

- Users need to scroll to access some actions and see certain information
- Users can't see come information like the legend and map info

Please fix the map on mobile so the height doesn't cause this. 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/6323bca3-04d9-4ce7-9ec5-9b6d2a83b6bf)

Here's a screencast. 

https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/a8417ba0-9c97-40a8-83ec-4d42eff680ca

**Comment by 10234567Z** [comment]
I can take on this issue, feel free to assign it to me!

**Comment by bacitracin** [comment]
Hey @10234567Z ! Just wanted to check in on this one. Any progress?

**Comment by 10234567Z** [comment]
> Hey @10234567Z ! Just wanted to check in on this one. Any progress?

Hey! Sorry actually I got busy with my clients and personal project. I will be done with this issue in few days utmost.

**Comment by bacitracin** [comment]
> > Hey @10234567Z ! Just wanted to check in on this one. Any progress?
> 
> Hey! Sorry actually I got busy with my work. I will be done with this issue in few days utmost.

Cool, thanks for the update! If you do have to drop this ticket, no worries, just comment here.
