### ISSUE TITLE
Improve map toggle

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/clean-and-green-philly#599]
The current map/list view toggle likely has usability problems. 

- The four squares icon likely isn't commonly recognizable as a view control, while other icons like filter, plus, minus are more commonly understood. 
- Being top left, it seems to blend into the interface and is likely overlooked. 

https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/d716ff82-44ec-4a83-b6a0-d8253ff4b93b

Making these improvements will likely improve the usability. [View Prototype](https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=6787%3A50004&mode=design&t=y0KxhTxmXHwc8O7w-1)

- Add a fixed button center bottom floating above the map and the list
  - Clicking this button toggles between the map and the list
- Remove the toggle from the top bar row. The row shouldn't need to change from desktop to mobile. 

This new button takes up extra space there, which overlaps with the legend. 
- Make the legend on mobile collapse to just an info icon
  - When users click on it the legend should fully appear
  - Clicking on the title should collapse the legend again

https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/03887bd2-76ec-4c1c-8c29-928bc41a1a4a

**Comment by amyyeung17** [comment]
I would like to work on this. :)

**Comment by bacitracin** [comment]
Assigned!
