### ISSUE TITLE
A11y: On narrower screens the Filter button has no text & announces as just "button"

### ISSUE THREAD

**Issue by bacitracin** [CodeForPhilly/clean-and-green-philly#603]
## Describe the task
When using a screenreader to navigate through the property page buttons they should always announce what they are, "button, Filter" or "button, Download". On desktop screen widths we show the text within the button, and that text is announced. When the screen is narrower, the text disappears. The download button has an aria-label, so it announces. The Filter button needs an `aria-label="Filter"` as well.

## Acceptance Criteria

- [ ] Go to the Find Properties page
- [ ] Resize the screen so that it text in the button disappears.
- [ ] Turn on screenreader. Navigate to the Filter button.
- [ ] It announces as "Filter button"

**Comment by 10234567Z** [comment]
I am ready to take this issue, I can tackle this

**Comment by bacitracin** [comment]
@10234567Z Assigned!
