### ISSUE TITLE
A11y: Apply hover styling on property cards when keyboard focus is on the card

### ISSUE THREAD

**Issue by bacitracin** [CodeForPhilly/clean-and-green-philly#604]
## Describe the task

Currently there is this hover styling for a property card
<img width="322" alt="Screenshot 2024-04-27 at 21 45 38" src="https://github.com/CodeForPhilly/vacant-lots-proj/assets/7329799/6c76c075-dec7-41f6-bc85-0069ded8ef3f">

When keyboard navigating to a card there is this styling. You can see a focus indicator but no background color on the full card.
<img width="309" alt="Screenshot 2024-04-27 at 21 45 46" src="https://github.com/CodeForPhilly/vacant-lots-proj/assets/7329799/dc2a8be4-ad3b-43af-81c3-d801d74d4f5d">

Ideally it would look like this on keyboard focus:
<img width="315" alt="Screenshot 2024-04-27 at 21 45 54" src="https://github.com/CodeForPhilly/vacant-lots-proj/assets/7329799/2e2e0220-2d14-4171-ac3b-824288277511">

## Acceptance Criteria

- [ ] TAB to a property card
- [ ] Focus ring appears around the address link
- [ ] Background color appears on the card

## Additional context

* Potentially useful: https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-within

**Comment by AZBL** [comment]
would like to be assigned please

**Comment by Moylena** [comment]
@AZBL what is the status for this?

**Comment by AZBL** [comment]
> @AZBL what is the status for this?

I pushed what I think resolves the issue and awaiting review.

**Comment by marvieqa** [comment]
Confirming this is already in staging! Just waiting for it to be merged to production.

**Comment by bacitracin** [comment]
This is live, so closing the issue.
