### ISSUE TITLE
A11Y: Focus issues on the Find Properties page

### ISSUE THREAD

**Issue by bacitracin** [CodeForPhilly/clean-and-green-philly#605]
## Describe the task
Keyboard
Right now when you are using a keyboard to navigate the property filter page
- If you TAB to a filter button and activate it with ENTER, the keyboard focus jumps to the first filter item in the section.
- If you are using a keyboard to select from one of the filter dropdowns, after activation the focus jumps back to the whole page.

Screenreader
- If you're using a screenreader and activate a filter, the focus jumps back to the entire Find Properties page, a disorienting and frustrating experience. 
- Same experience when using the dropdowns.

## Acceptance Criteria

- [ ] Ideally focus would remain on the filter/dropdown after selection/activation.

**Comment by Michael-Dratch** [comment]
Can I pick up this issue?

**Comment by bacitracin** [comment]
@Michael-Dratch assigned!

**Comment by Michael-Dratch** [comment]
Hi @bacitracin, I am have trouble reproducing the focus issues described in this issue. Is it possible that this issue is specific to certain browsers and screen reader tools. I'm currently using chrome and chrome's "Screen Reader" extension.

**Comment by bacitracin** [comment]
@Michael-Dratch This issue was written more than two months ago, so it's possible that it's been fixed/or was a dupe issue. I'll check it out, thanks for the heads up! Also just FYI generally testing is with one of the following popular browser/SR  combinations:

- JAWS/Chrome
- JAWS/Edge
- NVDA/FIrefox
- Safari/VoiceOver <-- what I test with

**Comment by bacitracin** [comment]
@Michael-Dratch Here's the link to NVDA, which you can download for free - https://www.nvaccess.org/download/

Forgot to say, you're right, each browser/screenreader combo acts differently, and so creating fixes that make all the screenreaders happy can be a bit of a headache.

**Comment by bacitracin** [comment]
@Michael-Dratch Looks like this was taken care of by @jgrimes86 when he did https://github.com/CodeForPhilly/clean-and-green-philly/issues/627. Closing this as a dupe!
