### ISSUE TITLE
Add necessary tooltips

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/clean-and-green-philly#612]
The icon buttons in the sceenshot below need tooltips to help explain their meaning. 

- Street View
- View on City Atlas
- Show my Location
- Zoom In
- Zoom Out

![Image](https://github.com/CodeForPhilly/clean-and-green-philly/assets/1965986/b4bdb87d-2432-4d1c-bd22-62d391e9c3b3)

The tooltip should be like the one on the Share button. 

![Image](https://github.com/CodeForPhilly/clean-and-green-philly/assets/1965986/18bc057e-49ea-4591-aa72-13f911fe8604)

**Comment by amyyeung17** [comment]
I would like to be assigned this. :)

**Comment by amyyeung17** [comment]
@thansidwell The MapLibre components already have title attribute tooltips. Do we still want to replace them with the stylized ones? It's possible, albeit more complex.

**Comment by thansidwell** [comment]
@amyyeung17 Yes, the styled tooltips are preferable to the native attribute tooltips. I think because they appear quicker, are often larger, match the rest of the interface, and present a more consistent experience across browsers and systems. 

<img width="322" alt="CleanShot 2024-05-15 at 15 31 18@2x" src="https://github.com/CodeForPhilly/clean-and-green-philly/assets/1965986/77fabe80-38c8-4964-95f8-2b906db367ce">
