### ISSUE TITLE
Add "park priority areas" data to parcels

### ISSUE THREAD

**Issue by nlebovits** [CodeForPhilly/clean-and-green-philly#62]
Add the "park priority areas" data from the ParkServe dataset to each parcel (will be used in identifying park need for recommended actions)

https://www.tpl.org/park-data-downloads

**Comment by nlebovits** [comment]
> Can I be assigned this task?

Yep! Just did it.

**Comment by nlebovits** [comment]
@Dev-solomon I recommend basically just reusing Brandon's approach in this module: https://github.com/CodeForPhilly/vacant-lots-proj/blob/main/data/src/data_utils/tree_canopy.py. The datasets should be super similar.

**Comment by sheelykyle** [comment]
Hey, assign me to this please :)

**Comment by Moylena** [comment]
@JosephAni  is this done?
