### ISSUE TITLE
Change ARIA attribute on Saved button

### ISSUE THREAD

**Issue by marvieqa** [CodeForPhilly/clean-and-green-philly#623]
## Describe

The ARIA attribute for the "Saved" button when selected is not appropriate. It is currently set to `<aria-current="true">`.  For the button's use-case, and to increase its understandability, we should change it to `<aria-pressed="true">` since this is essentially a toggle button.

<details>
<summary>Screen Shot</summary>

<img width="1407" alt="Screenshot 2024-05-05 at 15 51 55" src="https://github.com/CodeForPhilly/clean-and-green-philly/assets/102739972/889d6897-d4c5-4530-a625-fe05626ed687">

</details>

## Steps

1. Go to Find Properties page
2. Select a property -> click Save
3. Go back to property list -> Saved button is displayed
4. Select "Saved" -> inspect element

## Acceptance Criteria

- [ ] Change ARIA attribute to `<aria-pressed="true">`

**Comment by Amberroseweeks** [comment]
Hello! @marvieqa  i'd like to be assigned this issue. I might know why this is occurring, it's likely because of the style that is being used from the navigation buttons, we should edit the button component to remove that aria-label and only apply the `<aria-current="true">.`  to navigational/menu items like pagination and the menu.

**Comment by bacitracin** [comment]
@Amberroseweeks assigned! welcome back!

**Comment by bacitracin** [comment]
@Amberroseweeks Just a heads up, there have been a few PRs merged that are related to pagination. Not sure if that affects your work at all since this is the Saved button, but do work from the staging branch

**Comment by Amberroseweeks** [comment]
Thanks for the heads up @bacitracin , I am going to get started today so I'll be sure to work from staging.
