### ISSUE TITLE
Add descriptive aria label on "Saved" button

### ISSUE THREAD

**Issue by marvieqa** [CodeForPhilly/clean-and-green-philly#624]
## Describe the task

Improve the understandability of "Saved" button, by adding `<aria-label="Saved Properties">`

## Acceptance Criteria
- [ ] add `<aria-label="Saved Properties">` on "Saved" button

**Comment by CodeWritingCow** [comment]
@marvieqa or @Moylena can you assign this ticket to me? Thank you!

**Comment by bacitracin** [comment]
@CodeWritingCow i got u

**Comment by bacitracin** [comment]
Live
