### ISSUE TITLE
Keyboard focus is lost when toggling Filter button

### ISSUE THREAD

**Issue by marvieqa** [CodeForPhilly/clean-and-green-philly#627]
## Description

Using a keyboard, the focus is lost when I deactivate Filter button.

## Steps

1. Go to Find Properties page
2. Using your keyboard, press tab key until you get to the "Filter" button
3. Press ENTER or SPACE on your keyboard -> Filter options shows up, focus is kept on Filter button
4. Press ENTER or SPACE again to deactivate to hide filter options

**Actual**
- Keyboard focus is lost; it goes back to the body

**Expected**
- Keyboard focus is kept on the Filter button.

**Comment by jgrimes86** [comment]
@marvieqa or @Moylena could I work on this issue and issue #654 ?

**Comment by bacitracin** [comment]
@jgrimes86 assigned!
