### ISSUE TITLE
Limit Search to Philadelphia

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/clean-and-green-philly#629]
When users serach there can be many results that are not located in Philadelphia. 

![Image](https://github.com/CodeForPhilly/clean-and-green-philly/assets/1965986/31060b8e-c124-44c1-a74f-d82fb43385f7)

Please restrict the search to only addresses found in Philadelphia.

**Comment by jgrimes86** [comment]
@Moylena or @thansidwell can this be assigned to me?

**Comment by CodeWritingCow** [comment]
@jgrimes86 I just assigned the ticket to you. Thanks for tackling this!
