### ISSUE TITLE
DevOps: Add pr_checks_backend 

### ISSUE THREAD

**Issue by zackdreitzler** [CodeForPhilly/clean-and-green-philly#638]
## Describe the task
Add the pr_checks_backend.yml file as a GitHub Actions workflow. The goal of this is to show every developer/reviewer that a PR impacting the `data` folder can successfully build and run the `vacant-lots-proj`. This also sets a foundational workflow that can be used to run a data quality check, formatter, and/or linter checks.

## Acceptance Criteria

- [ ] The workflow should only trigger when changes are found in the `data` directory or any of the subdirectories
- [ ] The workflow should contain a `docker-compose run vacant-lots-proj` step
  - [ ] On success this step reports success to the PR that triggered this action
  - [ ] On failure this step reports a failure to the PR that triggered this action

## Additional context

This is currently blocked by #630. The postgres DB is required to get the docker build and run to be successful.

**Comment by nlebovits** [comment]
closed by #756
