### ISSUE TITLE
DevOps: Add formatter check to pr_checks_backend workflow

### ISSUE THREAD

**Issue by zackdreitzler** [CodeForPhilly/clean-and-green-philly#639]
## Describe the task
Add a formatter check to any PR impacting the `data` directory and its sub directories. This check ensures that new python code is formatted using the `black` formatter.

## Acceptance Criteria

- [ ] A format checking step exists on the pr_checks_backend workflow
- [ ] When all files report as formatted, report a success to the PR that triggered this action
- [ ] When one or more files report as not formatted, report a failure to the PR that triggered this action

## Additional context

This story is currently blocked until #638 is completed.

**Comment by Michael-Dratch** [comment]
Can I pick up this task?

**Comment by nlebovits** [comment]
closed by #756
