### ISSUE TITLE
DevOps: Add linting step to pr_checks_backend workflow

### ISSUE THREAD

**Issue by zackdreitzler** [CodeForPhilly/clean-and-green-philly#640]
## Describe the task
Add a linter check to any PR impacting the `data` directory and its sub directories. This check ensures that new python code is passing basic linting checks.

## Acceptance Criteria

- [ ] A linter checking step exists on the pr_checks_backend workflow
- [ ] When no issues are found, report a success to the PR that triggered this action
- [ ] When one or more issues are found, report a failure to the PR that triggered this action

## Additional context

This story is currently blocked until #638 is completed. This story is also blocked pending a decision on what python linter to use.

**Comment by nlebovits** [comment]
closed by #756
