### ISSUE TITLE
DevOps: Add unit testing step to the pr_checks_backend workflow

### ISSUE THREAD

**Issue by zackdreitzler** [CodeForPhilly/clean-and-green-philly#641]
## Describe the task
Add a unit testing check to any PR impacting the `data` directory and its sub directories. This check ensures that new python code is passing all unit tests

## Acceptance Criteria

- [ ] A unit test checking step exists on the pr_checks_backend workflow
- [ ] When no issues are found, report a success to the PR that triggered this action
- [ ] When one or more issues are found, report a failure to the PR that triggered this action

## Additional context

This story is currently blocked until #638 is completed. This story is also blocked pending a decision on what python unit test suite to use.

**Comment by nlebovits** [comment]
Issue #638 has been addressed so this ticket is ready to be worked on. Plus, we now have a unit test to run.
