### ISSUE TITLE
DevOps: Add unit testing step to the pr_checks workflow

### ISSUE THREAD

**Issue by zackdreitzler** [CodeForPhilly/clean-and-green-philly#642]
## Describe the task
Add a unit testing check to any PR impacting the frontend code. This check ensures that new JavaScript code is passing all unit tests.

## Acceptance Criteria

- [ ] A unit test checking step exists on the pr_checks workflow
- [ ] When no issues are found, report a success to the PR that triggered this action
- [ ] When one or more issues are found, report a failure to the PR that triggered this action

## Additional context

This story is also blocked pending a decision on what NextJS unit test suite to use.

**Comment by nlebovits** [comment]
The issue mentioned as a blocker has been completed, so this ticket can be worked on,

**Comment by nlebovits** [comment]
Project leads decided we won't write tests for the front end.
