### ISSUE TITLE
Change Saved button icon

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/clean-and-green-philly#646]
Currently when a user clicks the "Save" button
The text changes to "Saved"
That's not a very strong indicator that the property is saved. 

![Image](https://github.com/CodeForPhilly/clean-and-green-philly/assets/1965986/4d08cac1-a0b1-4145-8eae-e6abc46373fe)

When a user clicks the "Save" button 
**Change the icon to an check icon.** 
This better indicates to users that is it saved, rather than just the 

![Image](https://github.com/CodeForPhilly/clean-and-green-philly/assets/1965986/a1152463-822c-4ba7-a3e4-1655b71e6d59)

**Comment by zheyichn** [comment]
May I be assigned this ticket?
