### ISSUE TITLE
Methodology Page: Screen reader focus doesn't land on the intended heading.

### ISSUE THREAD

**Issue by marvieqa** [CodeForPhilly/clean-and-green-philly#650]
## Description

The "Learn more" links from the Filter UI point to span IDs in the Methodology page, where  upon navigating to it, the topic is framed beautifully in view.  However,  when using a screen reader this gets confusing. Here's an example:

Get Access "Learn More link" points to `/methodology/#access-method`
  <details>
  <summary>screenshot</summary>

  <img width="1223" alt="Screenshot 2024-05-26 at 23 08 31" src="https://github.com/CodeForPhilly/clean-and-green-philly/assets/102739972/15fc88c7-aedd-4634-ac96-abe88a9d6aa0">

  </details>

In Methodology page, this ID is pointing in this `<span>`, I believe because we wanted the "How did we determine “priority”?" heading to be centered in view:
  <details>
  <summary>Screenshot</summary>

  <img width="1272" alt="Screenshot 2024-05-26 at 23 12 35" src="https://github.com/CodeForPhilly/clean-and-green-philly/assets/102739972/50cf771c-1103-4de9-83d9-cbcd917af6bc">

  </details>

However, this is putting the screen reader focus on the paragraph above the intended heading, thus screen reader announces this first. 
A screen reader user may get thrown off when this paragraph is announced without a title or context, because coming from the Filter UI link we tell them this link goes to Methodology - Priority Level. The expectation would be that it announces the heading for Priority Level topic.

## Recommendation

- Put the span before the heading (or put the ID on the heading itself and test if it works), even if it means the heading will not be beautifully centered in view, so that screen reader announces the heading right away.

**Comment by jgrimes86** [comment]
Can I be assigned this one?
