### ISSUE TITLE
Filter: Neighborhood/Community Organization/Zone Pills: No accessible label for the pills x button

### ISSUE THREAD

**Issue by marvieqa** [CodeForPhilly/clean-and-green-philly#652]
## Description

In the Filters UI, when a neighborhood or a zone is selected from the list, we show a pill with an x button. The pill's x button doesn't contain an accessible name, thus screen reader users have no context of what this button does. More over these buttons are not discoverable in NVDA & Voice Over using the screen reader shortcuts.

<img width="1412" alt="Screenshot 2024-05-27 at 11 52 30" src="https://github.com/CodeForPhilly/clean-and-green-philly/assets/102739972/d38641e3-8b5f-4d41-a956-ad24e328dcd9">

## Recommendation
- give the x button an accessible name. Tie it to the pill name (ex. `<aria-label="clear Andorra">`

**Comment by JT0Y** [comment]
could I pull this issue?

**Comment by bacitracin** [comment]
@JT0Y sorry for the delay. assigned!
