### ISSUE TITLE
Property Details: Atlas link should also say "opens in a new tab"

### ISSUE THREAD

**Issue by marvieqa** [CodeForPhilly/clean-and-green-philly#659]
## Description

For consistency, we should use `aria-label` on the Atlas link to say "opens in a new tab" just like the links found in "Transform a Property Page"

## Acceptance Criteria

- [ ] add `<aria-label="Atlas, opens in a new tab">` on the Atlast link.

**Comment by KenMain5** [comment]
Can you assign this to me please?

**Comment by bacitracin** [comment]
@KenMain5 assigned
