### ISSUE TITLE
Filter: Make "Parcel Type" and "LLC Owner" filter options act like a checkbox

### ISSUE THREAD

**Issue by marvieqa** [CodeForPhilly/clean-and-green-philly#663]
## Description

Filter options under "Parcel Type" and "LLC Owner" are coded as toggle buttons. These don't provide much context of what these are about when using a screen reader, particularly if users are browsing for buttons. These buttons would just say "Yes", "No", "Land", or "Building", but no clear association of where they belong or what they are.

Instead, we should mark these up as a checkbox. 

## Acceptance Criteria

- use `<role=checkbox">` `<aria-checked="true">` to mimic a multi-select checkbox, rather than making these toggle buttons.
- associate these options to the filter heading so that users know what they are selecting for.

**Comment by Amberroseweeks** [comment]
I'd like to be assigned this issue, I believe I have a fix for this that is related to a PR I have right now

**Comment by bacitracin** [comment]
Assigned!
