### ISSUE TITLE
Bug: Selected Filter Panels Lose Their 'Selected' Appearance

### ISSUE THREAD

**Issue by jgrimes86** [CodeForPhilly/clean-and-green-philly#685]
**Describe the bug**
When a panel in the 'Get Access' section is selected, the color changes to its selected state.  However, if you toggle to the property card view and then back to the filter panel view, the panel no longer appears to be selected, even though the filter is still active.

**To Reproduce**
1. Go to the filter view.
2. Click on one or more panels in the 'Get Access' section to active those filters.
3. Exit the filter view so that you can see the property cards, then go back to the filter view.
4. See that the selected panels appear to not be active

**Expected behavior**
Filter panels will remain in their 'selected' state when toggling between the property card view and filter view

**Screenshots**
This is what a selected panel looks like when first selected.  It should continue to look like this as long as the filter is active:
![Filter showing panel selected](https://github.com/CodeForPhilly/clean-and-green-philly/assets/140654473/22d3313b-3c04-4ce6-b6c9-8acf9ca28bfa)

This is what the the selected panel currently looks like after leaving and returning to the filter view:
![Filter not showing panel selected](https://github.com/CodeForPhilly/clean-and-green-philly/assets/140654473/790e582c-5e0b-4649-936e-ade2893d5ac2)

**Comment by jgrimes86** [comment]
Also, I think I know how to correct this, so I would like to be assigned to it.  Thank you.

**Comment by nlebovits** [comment]
Assigned @jgrimes86!
