### ISSUE TITLE
Add "I want to help now!" button

### ISSUE THREAD

**Issue by nlebovits** [CodeForPhilly/clean-and-green-philly#69]
We would like to add a button to enable people to identify all the lots where they can take action immediately. This would basically be places where 1) they are high priority and 2) tactical urbanism is feasible (meaning that there would be minimal legal and safety obstacles to intervening immediately). The idea is to make it as easy as possible for people to instantly filter for these properties and find somewhere to help.

**Comment by nlebovits** [comment]
Should be easy to do on top of #142

**Comment by thansidwell** [comment]
I have some ideas of how this could work. I'm thinking there could be a button or buttons on the home page with something like "Help Now" and then maybe a dropdown or modal comes up asking how you would like to help. One option could just be "Clean some lots!" which could redirect you to the Map page filtered by the specific criteria.

**Comment by thansidwell** [comment]
I moved this back into Backlog while we get fill out what the design is.

**Comment by Moylena** [comment]
@thansidwell  @nlebovits since this isn't a part of the new design, should we close this?

**Comment by thansidwell** [comment]
@Moylena Yeah, we want to do it, but we haven't figured out the design. I'll just archive it.

**Comment by nlebovits** [comment]
This is still a good idea, but we need to punt it to our user research team to 1) understand how it would work, and 2) come up with a design. May open a new ticket later.
