### ISSUE TITLE
Bug: Cookie banner reappears after user accepts cookies

### ISSUE THREAD

**Issue by CodeWritingCow** [CodeForPhilly/clean-and-green-philly#701]
**Describe the bug**
After a user accepts cookies on the Clean & Green website, the cookie consent banner still appears whenever the user opens the site in a new browser window or tab.

**To Reproduce**
1. Go to https://www.cleanandgreenphilly.org.
2. Click on 'Accept' button in the cookie consent banner at the bottom of the screen.
3. Open a new browser window or tab, then go to https://www.cleanandgreenphilly.org.
4. Cookie banner will appear at the bottom of the screen in the new tab/window.

**Expected behavior**
If a user accepts having cookies on the website, and opens the site in a new browser window or tab, the cookie consent banner should not reappear.

**Screenshots**
Here is a screen recording of the bug:

https://github.com/CodeForPhilly/clean-and-green-philly/assets/7751862/3bf0fd88-e7c0-4da3-9bb4-a45fe488afa7

**Desktop**
 - OS: macOS
 - Browser: Google Chrome and Safari
 - Version: Chrome 126.0.6478.62, Safari 17.5

**Additional context**
This bug is related to Pull Request #635.

**Comment by JT0Y** [comment]
Greetings and salutations-
Could I take a whack at this and get this assigned to me? I was looking through the code and it looks like we aren't using local storage here. I have some test code that I can cleanup and further test if we are okay with that implementation.

**Comment by CodeWritingCow** [comment]
@JT0Y it's yours!
