### ISSUE TITLE
Store streetview images in a subdirectory in the Google Cloud bucket.

### ISSUE THREAD

**Issue by zigouras** [CodeForPhilly/clean-and-green-philly#717]
## Describe the task
Currently, Google streetview images are generated and stored in the root directory of the GCP bucket.  They should be in a subfolder like `streetview_images/` for better organization.
## Acceptance Criteria
The `streetview` service is defined the `docker-compose.yaml` file.  Update the code run by the service to write the image files to a sub-directory.
Update the front-end code to find images in the new sub-directory rather than in root.

## Additional context
None

**Comment by nlebovits** [comment]
I have a draft PR up for this issue, but I have other things that are higher priority for me to address. Will leave this for another dev to handle. See PR #894. I'll leave it up as a starting point until we get this issue addressed.

**Comment by nlebovits** [comment]
Not a priority right now--will tackle after the pipeline + database rewrite.
