### ISSUE TITLE
A11y: Remove 'aria-pressed' from mobile nav

### ISSUE THREAD

**Issue by bacitracin** [CodeForPhilly/clean-and-green-philly#727]
## Describe the task
Found this error by running the Axe Devtools  free browser extension https://chromewebstore.google.com/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US&pli=1.

The "aria-pressed" attribute isn't allowed on nav elements. This may have been built into the NextUI nav bar component that we're using for mobile. If possible, remove the aria-pressed (or overwrite it by passing in aria-pressed=undefined). It it's not possible to make these edits, comment on this ticket and we'll look into other approaches.

<img width="1188" alt="Screenshot 2024-07-02 at 12 33 29 PM" src="https://github.com/CodeForPhilly/clean-and-green-philly/assets/7329799/80211996-2475-4bc4-9d2f-3594601278a1">

## Acceptance Criteria

- [ ] Use Chrome Devtools to simulate mobile view
- [ ] Run Axe Devtools on the page
- [ ] You should not see the error from the screenshot.

## Resources
https://dequeuniversity.com/rules/axe/4.9/aria-allowed-attr?application=AxeChrome

**Comment by zheyichn** [comment]
Hi, can I be assigned this ticket?

**Comment by bacitracin** [comment]
@zheyichn assigned!

**Comment by zheyichn** [comment]
Tried the hints above "_remove the aria-pressed (or overwrite it by passing in aria-pressed=undefined)"_, these methods don't work as there is no `aria-pressed` passed around in our code. 
`aria-pressed` is generated becuase `NavbarMenuToggle` has the properties of a toggle button, and button can have that attr. 

An alternative approach is not setting it as a `navigation` component, and default to a toggle button. (i.e. remove `as="nav"`). What do you think ?@bacitracin 

<img width="1185" alt="remove-as-nav" src="https://github.com/CodeForPhilly/clean-and-green-philly/assets/88219993/57de6d55-4a3b-4638-b05e-68267a3ab798">

**Comment by bacitracin** [comment]
@zheyichn Thanks for looking into this one! Of course it's because of NextUI. Because of all the library's accessibility issues, honestly we will end up rewriting our own components at some point. See: https://github.com/CodeForPhilly/clean-and-green-philly/issues/728#issue-2386721891

While changing the role will remove the issue, we shouldn't remove the nav role. Screenreader users use landmarks to navigate the page. That would be removing functionality just to pass this "test." I think we'll just live with it for now, as when we eventually rewrite the hamburger nav it'll go away. Gonna close this issue.

**Comment by bacitracin** [comment]
Recap:
@zheyichn looked into this, and the issue came from NextUI. We plan to rewrite this hamburger menu eventually, so closing this issue for now.
