### ISSUE TITLE
Bug: Typo in docs > SETUP > BACK_END.md

### ISSUE THREAD

**Issue by csharpie** [CodeForPhilly/clean-and-green-philly#730]
The word recommended is spelled as _reccommended_. The extension for docker-compose.yaml should be written as .yml.

1. Go to docs > SETUP > BACK_END.md.
2. Review the sub-heading _Set Environment Variables_.
3. The last sentence is written as "A terminal emulator is reccommended."
4. Review the sub-heading _Docker Build_.
5. In the second paragraph, second sentence, the reference to the file _docker-compose.yml_ is written as "data/docker-compose.yaml".

The sentence under the sub-heading _Set Environment Variables_ should instead read "A terminal emulator is recommended." The file name referenced under the sub-headering Docker Build as docker-compose.yaml should instead read docker-compose.yml.

**Comment by csharpie** [comment]
@CodeWritingCow, thank you for reviewing and merging my pull request to the staging branch.

**Comment by csharpie** [comment]
I accidentally closed the issue.

**Comment by CodeWritingCow** [comment]
> @CodeWritingCow, thank you for reviewing and merging my pull request to the staging branch.

@csharpie thanks for contributing!
