### ISSUE TITLE
Task: Audit performance of 'Find Properties' page

### ISSUE THREAD

**Issue by CodeWritingCow** [CodeForPhilly/clean-and-green-philly#734]
## Describe the task

Audit performance of Clean and Green Philly's [Find Properties](https://www.cleanandgreenphilly.org/find-properties) webpage using Google Lighthouse. Document audit results, including areas of improvement.

## Acceptance Criteria

- [x] Generate Lighthouse report for mobile devices
- [x] Generate Lighthouse report for desktop devices
- [x] Post screenshots of results in this issue's comments section
- [x] Write brief summary of audit highlights, including Lighthouse's recommendations for improvement.

## Additional context

* For instructions on using Lighthouse, see https://developer.chrome.com/docs/lighthouse/overview

**Comment by zheyichn** [comment]
Hi! can I be assigned this issue pls?

**Comment by CodeWritingCow** [comment]
Hi @zheyichn this issue is yours!

Good question — yes, let's open it in an incognito window. I did the same thing because my browser has a bunch of dev-tool plugins, and they were affecting the performance score.

**Comment by zheyichn** [comment]
**Lighthouse report for mobile devices**
<img width="597" alt="find-mobile-1" src="https://github.com/CodeForPhilly/clean-and-green-philly/assets/88219993/5d55db4c-e708-439c-9e3b-2da97069d0b0">

**Comment by zheyichn** [comment]
## Lighthouse report for mobile devices

- Performance score was 60/100, mainly impacted by Largest Contentful Paint (3.2 seconds), and Cumulative Layout Shift (score 0.397, a good CLS score should be within 0.1).
- Accessibility score was 97/100. The only concern is that lists containing elements other than `<li>` and script-supporting elements can disrupt screen readers navigating the list.

### Screenshoots
![find-desktop-1](https://github.com/CodeForPhilly/clean-and-green-philly/assets/88219993/22a7d10a-b1ae-4fc6-8d28-509df73315c6)

![find-desktop-2](https://github.com/CodeForPhilly/clean-and-green-philly/assets/88219993/6269f940-9e7b-42f1-a113-cd8c9ede4e63)

![find-desktop-3](https://github.com/CodeForPhilly/clean-and-green-philly/assets/88219993/fea7207d-45cf-42c6-bcdb-7fceef81df7e)

![find-desktop-4](https://github.com/CodeForPhilly/clean-and-green-philly/assets/88219993/26a667fe-fa21-469f-a0e7-2dc26fda359c)

**Comment by zheyichn** [comment]
### Summary
Performance is hindered by long image loading times.
Accessiblity is acceptable on desktop, but needs further adjustments for mobile devices.

### Improvement recommendations

#### For mobile devices
1. Reduce largest contentful paint time by loading images faster. (Performance)
2. Check usage of `aria-*` attribute. (Accessibility)
3. Give `button` proper accessible names. (Accessibility)

#### For desktop devices
1. Reduce largest contentful paint time by loading images faster. (Performance)
2. Double check if we can make lists contain only `<li>`, `<script>`, `<template>`. (Accessibility)

**Comment by zheyichn** [comment]
Hi @CodeWritingCow Can you take a look when you get a sec? Let me know if anything needs to be added. Thanks!

**Comment by CodeWritingCow** [comment]
> Hi [@CodeWritingCow](https://github.com/CodeWritingCow) Can you take a look when you get a sec? Let me know if anything needs to be added. Thanks!

Hi @zheyichn this is great — your audit was extremely detailed and included good recommendations for improvement. Thank you.

Since the "Find Properties" page is the heart of our web application, I will create issues for improving its performance based on your recommendations.

Did Lighthouse identify any specific images that are causing the large contentful paint time?

**Comment by CodeWritingCow** [comment]
By the way, @bacitracin is testing our site for accessibility compliance on mobile. To avoid duplicating Tracy's work, I won't be creating a11y issues for this page for now. However, do feel free to share your a11y findings with her.

**Comment by zheyichn** [comment]
> > Hi [@CodeWritingCow](https://github.com/CodeWritingCow) Can you take a look when you get a sec? Let me know if anything needs to be added. Thanks!
> 
> Hi @zheyichn this is great — your audit was extremely detailed and included good recommendations for improvement. Thank you.
> 
> Since the "Find Properties" page is the heart of our web application, I will create issues for improving its performance based on your recommendations.
> 
> This page uses many images. Did Lighthouse identify any specific images that are causing the large contentful paint time? If there are specific images that are causing this problem, then we can focus on them.

Hi @CodeWritingCow, It is the logo image as below causing the delay. While I generated reports for other pages, they also complained about this logo image.
![image](https://github.com/user-attachments/assets/25d921d0-f8ee-4301-b439-d7a481586220)

**Comment by CodeWritingCow** [comment]
@zheyichn Since this logo image is part of the header UI, it appears on every page. If we fix the problem with this image, then we'll probably improve the performance score for other pages, too.
