### ISSUE TITLE
Task: Audit performance of Get Access page

### ISSUE THREAD

**Issue by CodeWritingCow** [CodeForPhilly/clean-and-green-philly#735]
## Describe the task

Audit performance of Clean and Green Philly's [Get Access ](https://www.cleanandgreenphilly.org/get-access) webpage using Google Lighthouse. Document audit results, including areas of improvement.

## Acceptance Criteria

- [ ] Generate Lighthouse report for mobile devices
- [ ] Generate Lighthouse report for desktop devices
- [ ] Post screenshots of results in this issue's comments section
- [ ] Write brief summary of audit highlights, including Lighthouse's recommendations for improvement.

## Additional context

* For instructions on using Lighthouse, see https://developer.chrome.com/docs/lighthouse/overview

**Comment by AZBL** [comment]
Hi I'd like to be assigned this.

**Comment by CodeWritingCow** [comment]
@AZBL assigned!

**Comment by AZBL** [comment]
## Summary
#### Desktop scoring for the Get Access page was good across the board. 
- **Performance**: 97
- **Accessibility**: 95
- **Best** **Practices**: 100
- **SEO**: 91

#### Mobile scoring did poorly on Performance and good elsewhere
- **Performance**: 97
- **Accessibility**: 95
- **Best Practices**: 100
- **SEO**: 91

#### Areas for Improvement (all on mobile):
- Reduce JavaScript execution time
- Minimize main-thread work
- Reduce unused JavaScript
- Eliminate render-blocking resources
- Reduce the impact of third-party code
- Largest Contentful Paint element - 2,800 ms
- Page prevented back/forward cache restoration


*******

![get_access_mobile_lighthouse_report](https://github.com/user-attachments/assets/e84e9cce-fd68-4c40-92d8-df91d85b07ce)
![get_access_lighthouse_report_desktop](https://github.com/user-attachments/assets/c05f2959-5c0a-4a30-8f64-8e8f97abfb4c)

**Comment by AZBL** [comment]
@CodeWritingCow If you create a ticket for improving the mobile performance could you assign it to me please

**Comment by CodeWritingCow** [comment]
> #### Mobile scoring did poorly on Performance and good elsewhere
> * **Performance**: 97
> * **Accessibility**: 95
> * **Best Practices**: 100
> * **SEO**: 91
> 

@AZBL I think Mobile's performance score is 69 and not 97. Can you fix that? Thanks!

**Comment by CodeWritingCow** [comment]
> [@CodeWritingCow](https://github.com/CodeWritingCow) If you create a ticket for improving the mobile performance could you assign it to me please

@AZBL definitely!
