### ISSUE TITLE
Task: Audit performance of Transform Property page

### ISSUE THREAD

**Issue by CodeWritingCow** [CodeForPhilly/clean-and-green-philly#736]
## Describe the task

Audit performance of Clean and Green Philly's [Transform a Property](https://www.cleanandgreenphilly.org/transform-property) webpage using Google Lighthouse. Document audit results, including areas of improvement.

## Acceptance Criteria

- [ ] Generate Lighthouse report for mobile devices
- [ ] Generate Lighthouse report for desktop devices
- [ ] Post screenshots of results in this issue's comments section
- [ ] Write brief summary of audit highlights, including Lighthouse's recommendations for improvement.

## Additional context

* For instructions on using Lighthouse, see https://developer.chrome.com/docs/lighthouse/overview

**Comment by nlebovits** [comment]
Will revisit performance later in 2025 after we've upgraded UI
