### ISSUE TITLE
Task: Audit performance of Legal Disclaimer page

### ISSUE THREAD

**Issue by CodeWritingCow** [CodeForPhilly/clean-and-green-philly#743]
## Describe the task

Audit performance of Clean and Green Philly's [Legal Disclaimer](https://www.cleanandgreenphilly.org/legal-disclaimer) page using Google Lighthouse. Document audit results, including areas of improvement.

## Acceptance Criteria

- [ ] Generate Lighthouse report for mobile devices
- [ ] Generate Lighthouse report for desktop devices
- [ ] Post screenshots of results in this issue's comments section
- [ ] Write brief summary of audit highlights, including Lighthouse's recommendations for improvement

## Additional context

* For instructions on using Lighthouse, see https://developer.chrome.com/docs/lighthouse/overview

**Comment by Skye967** [comment]
Can I get assigned to this?

**Comment by bacitracin** [comment]
@Skye967 assigned!

**Comment by Skye967** [comment]
# Mobile 
### Overview

![Screenshot 2024-07-25 at 11 46 19 AM](https://github.com/user-attachments/assets/3cd0cc92-306f-4648-9403-8147a24d4dfe)

## Recommendations 

1. Largest Contentful Paint takes over 7 seconds to load. Ensure the LCP element is displayed promptly by addressing any JavaScript tasks delaying rendering. Optimize JavaScript execution to prevent delays in rendering.
2. Reduce Javascript execution time. Preload late discovered resources, Render initial route ASAP, pre-cache remaining assets, and lazy load.
3. 1st party Resources are blocking the first paint of your page. Consider delivering critical JS/CSS inline and deferring all non-critical JS/styles.
4. Hotjar impacting load performance by 596ms. Load third-party code after your page has primarily finished loading. 

![Screenshot 2024-07-25 at 1 54 41 PM](https://github.com/user-attachments/assets/3818a7a9-f9eb-4eae-b188-50fdf10300f9)
![Screenshot 2024-07-25 at 1 54 53 PM](https://github.com/user-attachments/assets/09678674-2b24-4694-99e7-29f9e263117d)
![Screenshot 2024-07-25 at 1 55 08 PM](https://github.com/user-attachments/assets/59532a97-bc28-42b9-b3c5-04f0737b4a92)
![Screenshot 2024-07-25 at 1 55 23 PM](https://github.com/user-attachments/assets/5c5bbc27-1ced-4ebe-8d70-fb65b335b547)
![Screenshot 2024-07-25 at 1 55 39 PM](https://github.com/user-attachments/assets/a91394fd-5eb7-4603-883c-752e65e22e8a)
![Screenshot 2024-07-25 at 1 55 54 PM](https://github.com/user-attachments/assets/454fa1e0-2775-4ed4-a90b-42ecf5f863e8)
![Screenshot 2024-07-25 at 1 56 06 PM](https://github.com/user-attachments/assets/8a6c3827-a227-4cb2-ad3c-79a666b0906b)
![Screenshot 2024-07-25 at 1 56 27 PM](https://github.com/user-attachments/assets/7a5badc5-72cc-4281-993b-a3a048f92fa1)

# Desktop
### Overview

![Screenshot 2024-07-25 at 2 13 32 PM](https://github.com/user-attachments/assets/9d3432fb-565d-4103-9911-d7c8f6352c39)

### Recommendations

1. Reduce unused javascript from Hotjar and 1st party loading scripts until they are required.
2. 1st party resources are blocking the first paint of your page. Consider delivering critical JS/CSS inline and deferring all non-critical JS/styles.

![Screenshot 2024-07-25 at 2 20 00 PM](https://github.com/user-attachments/assets/dab90aa7-7308-4a7f-a4a1-ef26c9d65c80)
![Screenshot 2024-07-25 at 2 20 20 PM](https://github.com/user-attachments/assets/d991bf85-292c-4229-b401-2b7625ba1780)
![Screenshot 2024-07-25 at 2 21 14 PM](https://github.com/user-attachments/assets/7ff84a64-541a-4aff-b874-b0ac8da1af98)
