### ISSUE TITLE
Task: Audit performance of Request Removal page

### ISSUE THREAD

**Issue by CodeWritingCow** [CodeForPhilly/clean-and-green-philly#744]
## Describe the task

Audit performance of Clean and Green Philly's [Request Removal](https://www.cleanandgreenphilly.org/request-removal) page using Google Lighthouse. Document audit results, including areas of improvement.

## Acceptance Criteria

- [x] Generate Lighthouse report for mobile devices
- [x] Generate Lighthouse report for desktop devices
- [x] Post screenshots of results in this issue's comments section
- [x] Write brief summary of audit highlights, including Lighthouse's recommendations for improvement

## Additional context

* For instructions on using Lighthouse, see https://developer.chrome.com/docs/lighthouse/overview

**Comment by jgaye** [comment]
@CodeWritingCow here are the reports:

---

# Mobile
## Overview
![image](https://github.com/user-attachments/assets/78b60caa-dcce-4503-b9b4-310cc84d6697)

## Recommendations
1. LCP is the main text block and takes >5s to render after load, figure out how to reduce that. It could be cause by the element waiting for other elements to load
2. 1st party JS scripts take 2.8s to execute, reduce unused JavaScript and defer loading scripts until they are required to decrease bytes consumed by network activity
3. Hotjar load blocks the main thread and takes 480ms - try to load third-party code after your page has primarily finished loading

## Report link
https://pagespeed.web.dev/analysis/https-www-cleanandgreenphilly-org-request-removal/26cgqtlvoh?form_factor=mobile

## Performance issues details - High
![image](https://github.com/user-attachments/assets/6fc7a471-2197-4093-8223-9c77a89dc896)
![image](https://github.com/user-attachments/assets/227d6db6-d808-4495-a7de-716a026714d3)
![image](https://github.com/user-attachments/assets/2e9ba871-0188-4c8e-a868-f17d29e0d592)
![image](https://github.com/user-attachments/assets/fac71fe0-46a0-47c3-8be2-5677b397ca52)
![image](https://github.com/user-attachments/assets/dabc1f4d-85e5-4dc1-b0f2-02a8550b44e2)
![image](https://github.com/user-attachments/assets/eb805c06-59ba-4e67-86bd-68355121274f)

--- 

# Desktop
## Overview
![image](https://github.com/user-attachments/assets/931a5b6d-2e64-4669-8705-3cbecf772492)

## Recommendations
Already very good, but could be optimized by remove unused JS and CSS

## Report Link
https://pagespeed.web.dev/analysis/https-www-cleanandgreenphilly-org-request-removal/26cgqtlvoh?form_factor=desktop

## Performance issues details - High
![image](https://github.com/user-attachments/assets/97a46b61-16eb-4828-b012-3d747cb5b6b4)
![image](https://github.com/user-attachments/assets/34b36c8c-4951-4978-bbfa-222633ca345c)

**Comment by jgaye** [comment]
As I was trying to reproduce the low performance on my mobile phone and couldn't reproduce a load >1s I realized something:

**Note that the mobile performance is simulated for a slow 4g connection.** So do not be biased if the mobile page loads fast for you: users with a low 4G connection (bad reception at home, on the move, etc...) will have to wait 6secs to see the page.
![image](https://github.com/user-attachments/assets/ceb2a0bf-2430-4451-9513-07463ee26233)
