### ISSUE TITLE
Task: Improve performance of Accessibility Statement page

### ISSUE THREAD

**Issue by CodeWritingCow** [CodeForPhilly/clean-and-green-philly#745]
## Describe the task
Clean and Green Philly's [Accessibility Statement](https://www.cleanandgreenphilly.org/accessibility-statement) page has a Google Lighthouse performance score of 74/100 on mobile devices, compared to 97/100 on desktop devices. Reduce this page's image loading time and Improve the score to high 80s or low-to-mid 90s.

## Acceptance Criteria

- [ ] Reduce image loading time for Accessibility Statement page
- [ ] Generate Lighthouse report for mobile devices, showing improvement in performance score
- [ ] Post screenshots of results in this issue's comments section

## Additional context

* See #740 for details
* For instructions on using Lighthouse, see https://developer.chrome.com/docs/lighthouse/overview

**Comment by nlebovits** [comment]
Will revisit performance later in 2025 after we've upgraded UI
