### ISSUE TITLE
A11y: Windows High Contrast Mode: Filters page-Tactical Urbanism icon

### ISSUE THREAD

**Issue by bacitracin** [CodeForPhilly/clean-and-green-philly#746]
## Describe the bug
1. When in Windows High Contrast Mode / dark the gardening tool icon for Tactical Urbanism is hard to see.

Normal
<img width="507" alt="Screenshot 2024-07-15 at 10 19 35 AM" src="https://github.com/user-attachments/assets/bc311bda-b9fc-477e-a4a8-1e03cae4ac80">

High Contrast Mode
<img width="505" alt="Screenshot 2024-07-15 at 10 19 05 AM" src="https://github.com/user-attachments/assets/ee8bd94e-ba2c-459b-ba2d-d37a27bec8a1">

## Acceptance Criteria
Open the page in WHCM dark or simulate it using Devtools(see link below)
- [ ] The gardening tool icon will be easier to see / not gray  - will probably be white

## Additional context
* https://www.smashingmagazine.com/2022/06/guide-windows-high-contrast-mode/
* How to simulate WHCM in Chrome Devtools - https://devtoolstips.org/tips/en/emulate-forced-colors/

**Comment by zheyichn** [comment]
Hi, can I be assigned this ticket pls?

**Comment by bacitracin** [comment]
@zheyichn assigned!
