### ISSUE TITLE
A11y: Windows High Contrast Mode: Street View icon

### ISSUE THREAD

**Issue by bacitracin** [CodeForPhilly/clean-and-green-philly#748]
## Describe the bug
1. When in Windows High Contrast Mode / dark the expand to street view icon is hard to see

Normal
<img width="499" alt="Screenshot 2024-07-15 at 10 41 24 AM" src="https://github.com/user-attachments/assets/d1b7074f-fb34-41c5-a571-c1f8babeb27a">

High Contrast Mode
<img width="506" alt="Screenshot 2024-07-15 at 10 41 17 AM" src="https://github.com/user-attachments/assets/7382bcc7-2292-43b1-b85f-08d8b6086dbf">

## Acceptance Criteria
Open the page in WHCM dark or simulate it using Devtools(see link below)
- [ ] The icon will be visible against the background. Please don't hardcode the colors, use `ButtonText` for the color. See: https://www.smashingmagazine.com/2022/03/windows-high-contrast-colors-mode-css-custom-properties/

## Additional context
* https://www.smashingmagazine.com/2022/06/guide-windows-high-contrast-mode/
* How to simulate WHCM in Chrome Devtools - https://devtoolstips.org/tips/en/emulate-forced-colors/
* https://blogs.windows.com/msedgedev/2020/09/17/styling-for-windows-high-contrast-with-new-standards-for-forced-colors/

**Comment by zheyichn** [comment]
Hi, can I be assigned this issue? Thx.

**Comment by bacitracin** [comment]
@zheyichn assigned!
