### ISSUE TITLE
DevOps: Add precommit hook

### ISSUE THREAD

**Issue by nlebovits** [CodeForPhilly/clean-and-green-philly#759]
## Describe the task
Add a precommit hook to streamline the dev process. It should run formatters and linters for both the web app and the ETL pipeline, plus check dependencies and validate commit messages.

## Acceptance Criteria

- [ ] A `.pre-commit-config.yaml` file has been added to the root directory
- [ ] The precommit hook runs `eslint` and `prettier` for the web app
- [ ] The precommit hook runs `black` and `flake8` for the `data/` subdirectory
- [ ] The precommit hook runs `pip-compile` and `npm audit` or something similar to ensure dependencies are up to date
- [ ] The pre-commit hook uses something like `commitlint` to make sure commit messages are consistent + legible

**Comment by Michael-Dratch** [comment]
I'll pick up this task

**Comment by Michael-Dratch** [comment]
I ran into a blocker trying to incorporate the most recent changes to the repo into my PR for this ticket. The ESlist pre-commit hook is now raising a ton of errors and it seems that many code changes would be required to meet the default eslint standards. Not sure If I have the experience with ESlint and hooks to address these issue and wondering if I could hand this off or get some assistance fixing the remaining ESlint issues.  Here is my pre-commit config as is:

[pre-commit-config-yaml.txt](https://github.com/user-attachments/files/16394357/pre-commit-config-yaml.txt)

**Comment by SKalt** [comment]
@Michael-Dratch what would you think of PR'ing new linting rules one by one rather than all at once? Most of the times I introduced tools like `black`/`prettier` in the past my PRs touched most of the codebase. Enabling linting/formatting rules one by one takes more time, but it makes reviewing individual fixes much easier.

**Comment by CodeWritingCow** [comment]
> I ran into a blocker trying to incorporate the most recent changes to the repo into my PR for this ticket. The ESlist pre-commit hook is now raising a ton of errors and it seems that many code changes would be required to meet the default eslint standards. Not sure If I have the experience with ESlint and hooks to address these issue and wondering if I could hand this off or get some assistance fixing the remaining ESlint issues. Here is my pre-commit config as is:
> 
> [pre-commit-config-yaml.txt](https://github.com/user-attachments/files/16394357/pre-commit-config-yaml.txt)

@Michael-Dratch no worries about handing this off if you're running into problems. It looks like @nlebovits has submitted a PR for this ticket. So I've reassigned this ticket to Nissim. Thanks!
