### ISSUE TITLE
DevOps: remove unused imports + variables during precommit

### ISSUE THREAD

**Issue by nlebovits** [CodeForPhilly/clean-and-green-philly#837]
## Describe the task

Integrate a tool to automatically remove unused imports and variables from Python and JavaScript/TypeScript files into the pre-commit hooks. The suggested tools are `autoflake` for Python and `eslint-plugin-unused-imports` for JavaScript/TypeScript, but if there are better alternatives, feel free to use those instead.

## Acceptance Criteria

- [ ] Install a tool for automatically removing unused imports and variables from Python files (e.g., `autoflake`).
- [ ] Install a tool for automatically removing unused imports from JavaScript/TypeScript files (e.g., `eslint-plugin-unused-imports`).
- [ ] Update the pre-commit hook to include the chosen tools and ensure they run automatically before each commit.
- [ ] Validate that the tools are effectively removing unused imports and variables in the respective files.

**Comment by SKalt** [comment]
If you're OK with a different python linting tool, `ruff` supports fixing unused imports: https://docs.astral.sh/ruff/rules/unused-import/

**Comment by nlebovits** [comment]
@SKalt Agreed, I was actually leaning toward switching to `ruff`, which I've started using for other projects recently. I'll get a ticket up.

**Comment by nlebovits** [comment]
obsolete because of #841, which switches to `ruff`
