### ISSUE TITLE
Task: Add script to write latest dataset to zipped geoparquet or geojson

### ISSUE THREAD

**Issue by nlebovits** [CodeForPhilly/clean-and-green-philly#843]
## Describe the task
We often share the dataset with external partners. It would be good to automate this workflow, perhaps by implementing a single volume in docker like "docker compose write dataset" to quickly write out a local version of the latest data for sharing.

**Comment by zigouras** [comment]
Hi @nlebovits I looked at the PR and  the code looks fine.

The latest prod tiles file is available publicly at https://storage.googleapis.com/cleanandgreenphl/vacant_properties_tiles.pmtiles
Is there any reason we would not simply point partners to that file?

**Comment by nlebovits** [comment]
@zigouras partners' technical capacity is often limited, so it's nice to have the option to extract a file on demand in the filetype of their preference. I'm also wary of publicizing the fact that we have an open endpoint where people can grab the data. makes it too easy for predatory real estate developers if they know it's there. (I know they can figure it out if they're tech saavy, but every extra obstacle helps, imo.) I'm going to merge the code for now because it's convenient for me to have the service when I need it, but we can prune it if we feel it's no longer relevant in the future. Eventually we'll probably have a download button anyway, or some other kind of internal setup.

**Comment by nlebovits** [comment]
closed by #844
