### ISSUE TITLE
DevOps: automate weekly pull request from staging to main

### ISSUE THREAD

**Issue by nlebovits** [CodeForPhilly/clean-and-green-philly#849]
## Describe the task
We would like to consistently open a PR from `staging` to `main` each week on Sunday at midnight. This will give contributors time to address bugs during the week, rather than when folks are away during the weekend. Add a GitHub Actions workflow to open this PR.

## Acceptance Criteria

- [ ] A GitHub Actions workflow is created to open a PR from `staging` to `main` every Sunday at midnight.
- [ ] The workflow is tested to ensure it triggers correctly and opens a PR.
- [ ] Add an option to manually trigger the workflow.
- [ ] In instances where `staging` is not ahead of `main`, don't open the PR.

**Comment by brennenyu** [comment]
@nlebovits Would love to be assigned to this!

**Comment by nlebovits** [comment]
Yep! Assigned :)

**Comment by nlebovits** [comment]
@brennenyu How's this issue coming? Do you need any input from us?

**Comment by brennenyu** [comment]
@nlebovits Hi! Sorry this is taking a while. Been especially busy this past week. It's my first commit to an open-source repo so had to get acquainted with a lot of things, especially via fork and using git on the command line for that.

I have the script written down and am figuring out how to test it.

A small question I had was if you wanted the script to run at Sunday 12:00AM or Monday 12:00AM UTC. This is equivalent to Saturday 7:00-8:00PM or Sunday 7:00-8:00PM Eastern Time.

I was going to go Monday 12:00AM UTC based off what I inferred intent of the script was. What do you think?

Eager to help contribute to this project!
