### ISSUE TITLE
Task: Improve performance of homepage

### ISSUE THREAD

**Issue by CodeWritingCow** [CodeForPhilly/clean-and-green-philly#853]
## Describe the task
Clean and Green Philly's [homepage](https://www.cleanandgreenphilly.org/) has a Google Lighthouse performance score of 75/100 on mobile devices, compared to 99/100 on desktop devices. Reduce this page's image loading time and Improve the score to high 80s or low-to-mid 90s.

## Acceptance Criteria

- [ ] Investigate cause of image `Load delay` on homepage
- [ ] Reduce image load time
- [ ] Remove unused CSS — Avoid loading unnecessary CSS by splitting global.css file into smaller file specific to homepage
- [ ] Generate Lighthouse report for mobile devices, showing improvement in performance score
- [ ] Post screenshots of results in this issue's comments section

## Additional context

* See #733 for details
* For instructions on using Lighthouse, see https://developer.chrome.com/docs/lighthouse/overview

**Comment by nlebovits** [comment]
Will revisit performance later in 2025 after we've upgraded UI
