### ISSUE TITLE
Task: Fix Typos on the Accessibility Statement

### ISSUE THREAD

**Issue by bacitracin** [CodeForPhilly/clean-and-green-philly#857]
## Describe the task

1. Capitalize "Measures to support accessibility". Change to "Measures to Support Accessibility" to match other h2s.
2. Update the bullets on the Accessibility Statement

Under "Measures to support accessibility" it's currently:

Our team prioritizes accessibility by:
- Integrating accessibility as part of the design process Integrating
- accessibility in the development process Utilizing automated
- accessibility tools as part of our testing Designating an
- Accessibility Specialist that serves as a resource for our contributors

It should be updated so that each bullet starts with the capitalized letter.
- Integrating accessibility as part of the design process 
- Integrating accessibility in the development process 
- Utilizing automated accessibility tools as part of our testing 
- Designating an Accessibility Specialist that serves as a resource for our contributors

**Comment by zheyichn** [comment]
Hi, can I be assigned this issue pls?

**Comment by bacitracin** [comment]
@zheyichn assigned! thx for grabbing it
