### ISSUE TITLE
A11y: Accessibility Statement: Hide hr element from screenreaders

### ISSUE THREAD

**Issue by bacitracin** [CodeForPhilly/clean-and-green-philly#858]
## Describe the task

The separator at the bottom of the Accessibility Statement page is announced by screenreaders. Add `aria-hidden="true"` to the element to hide it.

![Screenshot 2024-08-02 at 11 33 53 AM](https://github.com/user-attachments/assets/d499db3a-91ec-4360-abc6-6d9a91b38ed2)

**Comment by zheyichn** [comment]
Hi, can i be assigned this issue pls?

**Comment by CodeWritingCow** [comment]
@zheyichn assigned!
