### ISSUE TITLE
Bug: Filter dropdowns are not displaying selected items

### ISSUE THREAD

**Issue by bacitracin** [CodeForPhilly/clean-and-green-philly#861]
**Describe the bug**
On the Find Properties page if you select an item from the dropdown, the selected item does not show. There's no way to know what you selected. Previously selected items showed as little pills inside the dropdown.

**To Reproduce**
1. Go to the Find Properties page. 
2. Click on the Filter button to open the filter pane. 
3. Scroll down to one of the 3 dropdown filters - Neighborhoods, Community Organizations, or Zoning.
4. Click the dropdown. Select an item.

**Expected behavior**
The selected item should show as a pill with an X to remove it.

**Screenshots**
You cannot see what was selected. The dropdown still says "Select options..."

**Comment by CodeWritingCow** [comment]
@jgrimes86 is working on this issue

**Comment by CodeWritingCow** [comment]
Hi @jgrimes86, I tried to assign you this ticket but wasn't able to. This repo might be set up so tickets can only be assigned to someone after they comment on it. Can you comment on this ticket so I can officially assign it to you? Thanks!

**Comment by jgrimes86** [comment]
Please assign me to this ticket.
