### ISSUE TITLE
Task: A11y Statement: Update VPAT link

### ISSUE THREAD

**Issue by bacitracin** [CodeForPhilly/clean-and-green-philly#870]
## Describe the task

Right now on the Accessibility Statement under Evaluation Report we have it as:

You can find our full evaluation report in VPAT®️ format. ([link](https://www.cleanandgreenphilly.org/vpat))

When you navigate through this with a screenreader it reads out as 
"You can find our full evaluation report in VPAT®️ format. ("
"link link"
")" which is strange. Let's change this to:

You can find our [full evaluation report in VPAT®️ format.](https://www.cleanandgreenphilly.org/vpat)

Which should read as 
"You can find our"
"link full evaluation report in VPAT®️ format."

**Comment by zheyichn** [comment]
Hi, can i be assigned this issue pls?
