### ISSUE TITLE
Task: Add definition of tactical urbanism

### ISSUE THREAD

**Issue by hannahvy** [CodeForPhilly/clean-and-green-philly#874]
## Describe the task

Collaborate with team to write and add the definition of **tactical urbanism** on Find Properties > clicked property.

## Acceptance Criteria

- [ ] Ensure the definition is understandable by non-experts.
- [ ] Potentially change Tactical Urbanism to an action item that starts with a verb for consistency with other action items listed (ie: Get permission..., Buy affordably...)
<img width="708" alt="image" src="https://github.com/user-attachments/assets/0c3b2bbe-7f52-478a-b011-7a84d98a9ee1">

## Additional context

- Idea: add informational "i" icon for in-depth definition.[ See here for example icons](https://thenounproject.com/browse/icons/term/information/).

**Comment by nlebovits** [comment]
Have discussed with UX team. Will convert to "Organize community cleanup" and move to interventions. Also forming a "temporary activation" working group to think about this further.
