### ISSUE TITLE
Task: Fix and hyperlink PA Horticultural Society on homepage

### ISSUE THREAD

**Issue by hannahvy** [CodeForPhilly/clean-and-green-philly#875]
## Describe the task

1. On the Homepage, correct Pennsylvania **Horticulture** Society to  Pennsylvania **Horticultural** Society under "Community groups and organizations are taking action."

2. Hyperlink this text to https://phsonline.org/, open in new tab.

**Comment by AZBL** [comment]
I'd like to be assigned this please.

**Comment by bacitracin** [comment]
Assigned!

**Comment by nlebovits** [comment]
closed by #905
