### ISSUE TITLE
Task: Ensure image corners are rounded consistently

### ISSUE THREAD

**Issue by tcmoorman** [CodeForPhilly/clean-and-green-philly#876]
## Describe the task

Per the prototype each image should have a corner radius of 20px. Two images on the homepage are not rounded

## Acceptance Criteria

- [ ] Correct rounding on homepage images

## Additional context
![Screen Shot 2024-08-15 at 11 13 07 PM](https://github.com/user-attachments/assets/b5dead93-e97d-4103-8ef8-0c0f16506d7a)
![Screen Shot 2024-08-15 at 11 13 13 PM](https://github.com/user-attachments/assets/78726b76-a0f4-4d15-b5b8-37a53069c20c)

- Add any other context about the task here.
- Or here

**Comment by CodeWritingCow** [comment]
@samipthapa please leave a comment on this ticket, asking it to be assigned to you. That way, we can officially assign this ticket to you and keep track of it. Thanks!
