### ISSUE TITLE
Task: GitHub Repository Links to Figma Prototype

### ISSUE THREAD

**Issue by tcmoorman** [CodeForPhilly/clean-and-green-philly#878]
## Describe the task

On the Methodology page, under the Data Sources header at the bottom, there is a link to the github repository. When clicked, the link pulls up a Figma page informing the user that they are being redirected to GitHub from Figma. To access the repo, the user must click the link on this Figma page

## Acceptance Criteria

- [ ] Link the GitHub repo without going through Figma first

**Comment by samipthapa** [comment]
@CodeWritingCow Created a pull request please review and merge

**Comment by samipthapa** [comment]
@CodeWritingCow
Created a pull request please review and merge

**Comment by CodeWritingCow** [comment]
@samipthapa thanks for contributing!
