### ISSUE TITLE
Task: Create a page for website architecture

### ISSUE THREAD

**Issue by mjnishigaki** [CodeForPhilly/clean-and-green-philly#881]
## Describe the task

Create a page on GitHub to explain to internal and external parties the architecture that exists for Clean and Green Philly

## Acceptance Criteria

- [ ] Create a diagram for the architecture for the website, including, but not limited to, other APIs and third party apps connected to the website and how the front end and back end components are associated.
- [ ] Relate this diagram to the front-end and back-end contributor pages/repos.
- [ ] Add links to the contributor guides where the contributor can find the architecture details.

## Additional context

-

**Comment by nlebovits** [comment]
Closing. Not high enough priority relative to other needs for development + documentation (e.g., need to improve data documentation, pipeline documentation, website "about" page content before we put effort into diagramming website architecture).
