### ISSUE TITLE
"Get permission from owner" Filter search criteria

### ISSUE THREAD

**Issue by tcmoorman** [CodeForPhilly/clean-and-green-philly#902]
Describe the bug
When selecting acquisition methods on the filter page, methods should be exclusive rather than inclusive. Adding another method to the filter should decrease the number of properties. When the option "Get permission from owner" is selected, the search becomes inclusive, showing all properties which share "Get permission from owner" and the selected acquisition methods.

To Reproduce
View all properties on the map, and select "Get permission" and any number of other acquisition methods. Compare to selecting multiple methods without Get permission selected. The number of properties increases when Get permission is added to the selection

**Comment by nlebovits** [comment]
Closing for now. Will integrate this into our 2025 roadmap. Tommy will rewrite.
