### ISSUE TITLE
Task: Set up `pytest` for back end

### ISSUE THREAD

**Issue by nlebovits** [CodeForPhilly/clean-and-green-philly#916]
## Describe the task

Set up `pytest` for the repository to enable automated testing. This includes installing `pytest` as a dependency, configuring the test environment, and ensuring basic test discovery functionality.

## Acceptance Criteria

- [ ] Install `pytest` as a development dependency in the project (`pip install pytest`).
- [ ] Use the existing test to confirm that it runs correctly.
- [ ] Ensure pytest automatically discovers and runs tests from all `test_*.py` files.

## Additional context

- `pytest` should be configured in the project to support future automated test setups.
- Consider integrating pytest into any CI/CD pipelines later as needed.

**Comment by jinks145** [comment]
I am on it!

**Comment by nlebovits** [comment]
hey @jinks145 how's this coming along? do you need any input from us?

**Comment by jinks145** [comment]
I have been a little swamped with job search preparation lately. But, I do have couple tests that I've been working on.
