### ISSUE TITLE
Task: Add Data Disclaimer overlay to Find Properties page

### ISSUE THREAD

**Issue by hannahvy** [CodeForPhilly/clean-and-green-philly#917]
## Describe the task

Implement a pop-up disclaimer to inform users that the City of Philadelphia has stopped recent data collection for vacant properties. User should have the option to click "I understand" or "X" button in upper right to close pop-up.

![image](https://github.com/user-attachments/assets/a6897bf7-5d93-47dc-9aa1-205203822e06)

**Comment by Amberroseweeks** [comment]
@hannahvy could you share a figma link or send the text so I can copy and paste it? Thank you!

**Comment by zigouras** [comment]
Instead of an overlay can we just make this a static piece of text on the page somewhere.  It is important enough to display all the time and the interruption of an overlay always seems intrusive to me.

**Comment by nlebovits** [comment]
closed by #956
