### ISSUE TITLE
Task: Logo redesign

### ISSUE THREAD

**Issue by mjnishigaki** [CodeForPhilly/clean-and-green-philly#928]
## Describe the task

C&G wants a logo redesign for the current logo in use. As of now, it is something that would be easy to rebrand since we have limited assets, no merch, etc. For this new logo, we need this item to be high definition and usable on our website and logo that would suffice for profile photos across online avenues.

## Acceptance Criteria
- [ ] we want map iconography in the photo

## Additional context
n/a

**Comment by nlebovits** [comment]
Closing this for now, as branding has become a larger consideration (i.e., much bigger than just a new logo) that we will tackle in 2025. Will wait until that's done before adding new logo, site content, etc.
