### ISSUE TITLE
Task: Replace current logo.svg with minified logo.svg

### ISSUE THREAD

**Issue by AZBL** [CodeForPhilly/clean-and-green-philly#930]
## Describe the task

The original logo.svg is 9447 bytes. The minified is 5547 bytes without any noticeable loss of quality. Ideally the difference would speed up performance a bit.  Here is the minified version. 

![logo](https://github.com/user-attachments/assets/2a306392-ffe7-4125-bfa8-08cf66301335)

**Comment by AZBL** [comment]
@CodeWritingCow – I don't believe I can assign myself this.

**Comment by nlebovits** [comment]
@AZBL assigned! thanks for catching

**Comment by nlebovits** [comment]
closed by #933
