### ISSUE TITLE
Mobile nav - Donate option is not visible in dropdown

### ISSUE THREAD

**Issue by bacitracin** [CodeForPhilly/clean-and-green-philly#976]
**Describe the bug**
On narrow screens the navigation switches to the hamburger menu and dropdown. The new Donate page is at the bottom of the nav, but you can't see it and can barely click on it with the. mouse.

**To Reproduce**

1. Click on "Donate" in the nav.
2. Narrow the width of the screen to get the nav to switch to the hamburger icon.
3. Click on the hamburger icon to trigger the nav dropdown to show

**Expected behavior**
You should be able to see the Donate option fully.

**Screenshots**
<img width="523" alt="Screenshot 2024-10-27 at 12 02 15 AM" src="https://github.com/user-attachments/assets/df3a23c0-a821-459b-81e6-362b2ad49d39">

**Comment by vinhyan** [comment]
Hi @bacitracin! I'd like to look into this issue please :)

**Comment by bacitracin** [comment]
@vinhyan assigned!

**Comment by bacitracin** [comment]
@vinhyan sure thing, i just created the label & added it

**Comment by vinhyan** [comment]
Closed by PR #985 @bacitracin @CodeWritingCow.

**Comment by vinhyan** [comment]
This should be closed by PR #985, but I'm not seeing the close option @bacitracin.

**Comment by vinhyan** [comment]
Closed by #985 @bacitracin.
